PoryectoPr5.UI/Controllers/artEstraviadosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using PoryectoPr5.UI.ServiceWCF;
using ProyectoPr5.DAL;

namespace PoryectoPr5.UI.Controllers
{
    public class artEstraviadosController : Controller
    {
        private ProyectoPR5Entities db = new ProyectoPR5Entities();

        // GET: artEstraviados
        public ActionResult Index()
        {
            var artEstraviados = db.artEstraviados.Include(a => a.Categoria);
            return View(artEstraviados.ToList());
        }

        public ActionResult Index2()
        {
            var artEstraviados = db.artEstraviados.Include(a => a.Categoria);
            return View(artEstraviados.ToList());
        }


        public ActionResult notificarUsuarios()
        {
            return View();
        }

        [HttpPost]
        public ActionResult enviarMail(Models.ContactarModel nuevo)
        {

            MailMessage mmsg = new MailMessage();

            var r = ProyectoPr5.BL.Clases.ManUsuarioss._Instancia.Mostrar();

            var correosx = (from a in r
                            select new { a.correo }).ToList();
            try { 
            bool ok = false;
            string toCorreo;
            foreach (var ele in correosx)
            {
                toCorreo = ele.correo;
                if (toCorreo != null)
                {
                    mmsg.To.Add(toCorreo);
                    mmsg.Subject = ("Articulo Nuevo Ingresado");
                    mmsg.SubjectEncoding = System.Text.Encoding.UTF8;
                    mmsg.Body = nuevo.mensaje;
                    mmsg.BodyEncoding = System.Text.Encoding.UTF8;
                    mmsg.IsBodyHtml = true;
                    mmsg.From = new System.Net.Mail.MailAddress("proyectopr52018@gmail.com");

                    SmtpClient cliente = new SmtpClient();
                    cliente.Credentials = new NetworkCredential("proyectopr52018@gmail.com", "hola123@");
                    cliente.Port = 587;
                    cliente.EnableSsl = true;
                    cliente.Host = "smtp.gmail.com";

                    try
                    {
                        cliente.Send(mmsg);
                        ok = true;
                    }
                    catch (Exception)
                    {


                    }
                }

           

        }

            if (ok)
            {
                TempData["msg"] = "<script>alert('Correos Enviados Satisfactoriamente');</script>";
            }
        }catch (Exception) {
            }
                ModelState.Clear();
            return View("notificarUsuarios");

        }



        // GET: artEstraviados/Create
        public ActionResult Create()
        {
            ViewBag.idCategoria = new SelectList(db.Categoria, "idCategoria", "nombreCategoria");
            return View();
        }

        // POST: artEstraviados/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idArticuloExt,nombre,idCategoria,FechaIngreso,descripcion,IngresadoPor,Telefono_Contacto")] artEstraviados artEstraviados)
        {
            if (ModelState.IsValid)
            {
                /*  db.artEstraviados.Add(artEstraviados);
                  db.SaveChanges();
                  return RedirectToAction("Index");*/

                Service1Client service = new Service1Client();
                service.AgregarArtExtraviados(artEstraviados);
                service.Close();

            }

            ViewBag.idCategoria = new SelectList(db.Categoria, "idCategoria", "nombreCategoria", artEstraviados.idCategoria);
            return View(artEstraviados);
        }





        public ActionResult Create2()
        {
            ViewBag.idCategoria = new SelectList(db.Categoria, "idCategoria", "nombreCategoria");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create2([Bind(Include = "idArticuloExt,nombre,idCategoria,FechaIngreso,descripcion,IngresadoPor,Telefono_Contacto")] artEstraviados artEstraviados)
        {
            if (ModelState.IsValid)
            {
                /*db.artEstraviados.Add(artEstraviados);
                db.SaveChanges();
                ModelState.Clear();
                return RedirectToAction("Create2");*/

                Service1Client service = new Service1Client();
                service.AgregarArtExtraviados(artEstraviados);
                service.Close();
            }

            ViewBag.idCategoria = new SelectList(db.Categoria, "idCategoria", "nombreCategoria", artEstraviados.idCategoria);
            return View("../HomeGuest/Index");
        }






        // GET: artEstraviados/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            artEstraviados artEstraviados = db.artEstraviados.Find(id);
            if (artEstraviados == null)
            {
                return HttpNotFound();
            }
            return View(artEstraviados);
        }

        // POST: artEstraviados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            /* artEstraviados artEstraviados = db.artEstraviados.Find(id);
             db.artEstraviados.Remove(artEstraviados);
             db.SaveChanges();
             ;*/


            var sss = new artEstraviados();
            sss.idArticuloExt = id;

            Service1Client service = new Service1Client();
            service.EliminarArtExtraviados(sss);
            service.Close();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PoryectoPr5.UI/Views/artEstraviados/Create.cshtml
@model ProyectoPr5.DAL.artEstraviados

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutCustodia.cshtml";
}

<h2>Agregar Articulos Extraviado</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Categoria", htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-10">
            @Html.DropDownList("idCategoria", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idCategoria, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.Label("Descripcion Articulo", htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.IngresadoPor, htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IngresadoPor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IngresadoPor, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefono_Contacto, htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Telefono_Contacto, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefono_Contacto, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-1 col-md-5">
            <input type="submit" value="Agregar Articulo" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Volver", "Index")
</div>

PoryectoPr5.UI/Views/artEstraviados/Create2.cshtml
@model ProyectoPr5.DAL.artEstraviados

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutGuest.cshtml";
}

<h2>Agregar Articulos Extraviado</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("Nombre del Articulo", htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Categoria", htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-10">
            @Html.DropDownList("idCategoria", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idCategoria, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.Label("Descripcion Articulo", htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.IngresadoPor, htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IngresadoPor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IngresadoPor, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefono_Contacto, htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Telefono_Contacto, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefono_Contacto, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-1 col-md-5">
            <input type="submit" value="Agregar Articulo" class="btn btn-primary" />
        </div>
    </div>
</div>
}

PoryectoPr5.UI/Views/artEstraviados/Delete.cshtml
@model ProyectoPr5.DAL.artEstraviados

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutCustodia.cshtml";
}

<h2>Mover a articulo en Custodia</h2>


<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaIngreso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaIngreso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria.nombreCategoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.nombreCategoria)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Mover a Custodia" class="btn btn-default" /> |
            @Html.ActionLink("Volver", "Index")
        </div>
    }
</div>

PoryectoPr5.UI/Views/artEstraviados/Index.cshtml
@model IEnumerable<ProyectoPr5.DAL.artEstraviados>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutCustodia.cshtml";
}

<h2>Articulos Extraviados Actualmente</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Nombre del Articulo")
        </th>
        <th>
            @Html.DisplayName("Fecha de Ingreso")
        </th>
        <th>
            @Html.DisplayName("Descripcion Articulo")
        </th>
        <th>
            @Html.DisplayName("Categoria")
        </th>
        <th>
            @Html.DisplayName("Ingresado Por")
        </th>
        <th>
            @Html.DisplayName("Contacto")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaIngreso)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categoria.nombreCategoria)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IngresadoPor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefono_Contacto)
        </td>
        <td>
            @Html.ActionLink("Articulo encontrado. Mover a Custodia", "Delete", new { id = item.idArticuloExt })
        </td>
    </tr>
}

</table>


<p>
    @Html.ActionLink("Agregar nuevo articulo Extraviado", "Create")
</p>

PoryectoPr5.UI/Views/artEstraviados/notificarUsuarios.cshtml
@model PoryectoPr5.UI.Models.ContactarModel

@{
    Layout = "~/Views/Shared/_LayoutCustodia.cshtml";
}

@Html.Raw(TempData["msg"])
@using (Html.BeginForm("enviarMail", "artEstraviados", FormMethod.Post))
{
    <div class="container">
        <div class="card card-register mx-auto mt-5">
            <div class="card-header">Mensaje para contactos</div>
            <div class="card-body">

                <div class="form-group">
                    <div class="form-row">
                        <div class="col-md-6">

                        </div>
                    </div>
                </div>

                <br />
                <div class="form-group">
                    <div class="form-row">
                        <div class="col-md-6">
                            <div class="form-label-group">
                                @Html.TextAreaFor(model => model.mensaje, new { @class = "form-control bg-primary", required = "required", rows = "5" })

                                <label for="inputPassword">Ingrese el mensaje antes de enviar</label>
                            </div>
                        </div>

                    </div>
                </div>
                <br /><br />


            </div>


        </div>
    </div>
    <br>
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Enviar el Mensaje a todos lo usuarios" class="btn btn-primary col-md-4" />
    </div>
}